#! /usr/bin/env python3
# helper/make_packed.py

import os
import sys

if (len(sys.argv) < 4):
    print("Usage: make_packed.py <raw.bin> <xor_key_hex> <out_c_file>")
    sys.exit(1)

raw_file = sys.argv[1]
key = int(sys.argv[2], 16) & 0xFF
out_c = sys.argv[3]

with open(raw_file, "rb") as f:
    data = f.read()

packed = bytes([b ^ key for b in data])

os.makedirs(os.path.dirname(out_c), exist_ok=True)

with open(out_c, "w") as f: 
    f.write("/* generated by make_packed.py */ \n")
    f.write("#include <stdint.h>\n\n")
    f.write("static const uint8_t packed_code[] = { \n")
    for i in range(0, len(packed), 12):
        chunk = packed[i: i+12]
        line = ", ".join("0x%02x" % b for b in chunk)
        f.write("    " + line +("," if 1+12 < len(packed) else "") + "\n")
    f.write("};\n")
    f.write("static const size_t packed _len = %d;\n" % len(packed))

print("Wrote", out_c)



